services:
  ruby-app:
    build: .
    container_name: revibot
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - ./log:/rails/log
    environment:
      - RAILS_ENV=development
    tty: true
